fix an error in the workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -7,7 +7,6 @@ on:
 env:
   AWS_REGION: ${{ secrets.AWS_REGION }}
   ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
-  ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
   #CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
   #DEPLOYMENT_NAME: ${{ secrets.DEPLOYMENT_NAME }}
   #CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
@@ -37,20 +36,20 @@ jobs:
           if [ -f VERSION ]; then
             VERSION=$(cat VERSION)
           else
-           echo "VERSION file not found. Exiting..."
-           exit 1
+            echo "VERSION file not found. Exiting..."
+            exit 1
           fi
+          echo "version=$VERSION" >> $GITHUB_OUTPUT
           echo "Current version: $VERSION"
-          echo ::set-output name=version::$VERSION
 
       - name: Build Docker image
         run: |
-          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.get-version.outputs.version }} .
-
-      - name: Tag Docker image with semantic version
-        run: |
-          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.get-version.outputs.version }} $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.get-version.outputs.version }}
+          docker build -t ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.get-version.outputs.version }} .
+        env:
+          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
       
       - name: Push Docker image to ECR
         run: |
-          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.get-version.outputs.version }}
+          docker push ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.get-version.outputs.version }}
+        env:
+          ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
